version: '3'
services:
  web:
    build:
      context: .
    command: sh -c "./run.sh"
    volumes:
      - .:/app
      - /app/staticfiles
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:latest
  celery:
    build:
      context: .
    command: celery -A project worker --loglevel=info
    depends_on:
      - db
      - redis
    env_file:
      - .env
volumes:
  postgres_data: